produtos = ('Chocolate', 10.00,'Cigarro', 9.75, 'Biscoito',2.50)
print('------------LISTA DE PRODUTOS -------------')
print(f'{produtos[0]}----------R${produtos[1]:.2f}')
print(f'{produtos[2]}------------R${produtos[3]:.2f}')
print(f'{produtos[4]}-----------R${produtos[5]:.2f}')
print('----'*11)